version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run: 
          name : "Building Docker image with Ansible for Circleci"
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo "Building version ${TAG}:"
            docker build -t ansible-circleci:$TAG -f /home/circleci/project/Dockerfile .
            docker tag ansible-circleci:$TAG $DOCKERHUB_USER/ansible-circleci:$TAG
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker push $DOCKERHUB_USER/ansible-circleci:$TAG
            echo "The image has been pushed in this repository => ${DOCKERHUB_USER}/ansible-circleci:${TAG}"
            rm -f /home/circleci/.docker/config.json